/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param hasAccess
 * @param name
 * @param created ISO_TIMESTAMP
 * @param modified ISO_TIMESTAMP
 * @param isTierDefault
 * @param id
 */

data class AccessFeature(

    @Json(name = "has_access")
    val hasAccess: kotlin.Boolean,

    @Json(name = "name")
    val name: kotlin.String,

    /* ISO_TIMESTAMP */
    @Json(name = "created")
    val created: kotlin.String,

    /* ISO_TIMESTAMP */
    @Json(name = "modified")
    val modified: kotlin.String,

    @Json(name = "is_tier_default")
    val isTierDefault: kotlin.Boolean,

    @Json(name = "id")
    val id: kotlin.String

)
