/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param nextPage
 * @param activity
 */

data class ActivityLogs(

    @Json(name = "next_page")
    val nextPage: kotlin.String? = null,

    @Json(name = "activity")
    val activity: kotlin.collections.List<ActivityLog>? = null

)
