/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param actionLogin
 * @param city
 * @param actionDescription
 * @param region
 * @param ts ISO timestamp
 * @param subRegion
 * @param user
 * @param countryCode
 * @param action
 * @param orgGuid
 * @param id
 * @param metadata
 */

data class ActivityLog(

    @Json(name = "action_login")
    val actionLogin: kotlin.String? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "action_description")
    val actionDescription: kotlin.String? = null,

    @Json(name = "region")
    val region: kotlin.String? = null,

    /* ISO timestamp */
    @Json(name = "ts")
    val ts: kotlin.String? = null,

    @Json(name = "sub_region")
    val subRegion: kotlin.String? = null,

    @Json(name = "user")
    val user: kotlin.String? = null,

    @Json(name = "country_code")
    val countryCode: kotlin.String? = null,

    @Json(name = "action")
    val action: kotlin.String? = null,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "metadata")
    val metadata: kotlin.Any? = null

)
