/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param keywordLink
 * @param hash
 * @param newChannelBitlink
 * @param channelGuid
 * @param url
 * @param bitlinkCreatedTs
 * @param title
 * @param otherLinkError
 * @param shortenLinkError
 * @param globalHash
 * @param longUrl
 * @param channelBitlinkError
 */

data class AddBitlinkResult(

    @Json(name = "keyword_link")
    val keywordLink: kotlin.String? = null,

    @Json(name = "hash")
    val hash: kotlin.String? = null,

    @Json(name = "new_channel_bitlink")
    val newChannelBitlink: kotlin.Boolean? = null,

    @Json(name = "channel_guid")
    val channelGuid: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "bitlink_created_ts")
    val bitlinkCreatedTs: kotlin.Int? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "other_link_error")
    val otherLinkError: kotlin.String? = null,

    @Json(name = "shorten_link_error")
    val shortenLinkError: kotlin.String? = null,

    @Json(name = "global_hash")
    val globalHash: kotlin.String? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "channel_bitlink_error")
    val channelBitlinkError: kotlin.String? = null

)
