/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * the add on settings associated with the tier
 *
 * @param limit
 * @param price
 * @param featureName
 * @param product
 * @param incr
 */

data class AddOnSetting(

    @Json(name = "limit")
    val limit: kotlin.Int? = null,

    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    @Json(name = "feature_name")
    val featureName: kotlin.String? = null,

    @Json(name = "product")
    val product: kotlin.String? = null,

    @Json(name = "incr")
    val incr: kotlin.Int? = null

)
