/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * an add on purchase request
 *
 * @param featureName
 * @param quantity
 */

data class AddOn(

    @Json(name = "feature_name")
    val featureName: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal? = null

)
