/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * a list of add-ons entitlements that an org wants to purchase
 *
 * @param addOns
 */

data class AddOns(

    @Json(name = "add_ons")
    val addOns: kotlin.collections.List<AddOn>? = null

)
