/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param amountPurchased
 * @param amountUsed
 * @param amountAvailableForPurchase
 */

data class AddOnUsage(

    @Json(name = "amount_purchased")
    val amountPurchased: kotlin.Int? = null,

    @Json(name = "amount_used")
    val amountUsed: kotlin.Int? = null,

    @Json(name = "amount_available_for_purchase")
    val amountAvailableForPurchase: kotlin.Int? = null

)
