/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param cohort
 * @param identifier
 * @param entityType
 */

data class AddToCohort(

    @Json(name = "cohort")
    val cohort: kotlin.Int? = null,

    @Json(name = "identifier")
    val identifier: kotlin.String? = null,

    @Json(name = "entity_type")
    val entityType: kotlin.String? = null

)
