/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param priority
 * @param fallback
 * @param appGuid
 * @param os
 */

data class AppAssociationDetail(

    @Json(name = "priority")
    val priority: kotlin.Int? = null,

    @Json(name = "fallback")
    val fallback: kotlin.Boolean? = null,

    @Json(name = "app_guid")
    val appGuid: kotlin.String? = null,

    @Json(name = "os")
    val os: kotlin.String? = null

)
