/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param androidInstallPreference
 * @param iosInstallPreference
 * @param androidApps
 * @param customDomain
 * @param iosApps
 */

data class AppAssociations(

    @Json(name = "android_install_preference")
    val androidInstallPreference: InstallPreference? = null,

    @Json(name = "ios_install_preference")
    val iosInstallPreference: InstallPreference? = null,

    @Json(name = "android_apps")
    val androidApps: kotlin.collections.List<AppAssociationDetail>? = null,

    @Json(name = "custom_domain")
    val customDomain: kotlin.String? = null,

    @Json(name = "ios_apps")
    val iosApps: kotlin.collections.List<AppAssociationDetail>? = null

)
