/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param app
 * @param id
 * @param clientId
 * @param created ISO timestamp
 */

data class Authorization(

    @Json(name = "app")
    val app: OAuthAppWithOwnerLogin? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "client_id")
    val clientId: kotlin.String? = null,

    /* ISO timestamp */
    @Json(name = "created")
    val created: kotlin.String? = null

)
