/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param units
 * @param facet
 * @param unitReference
 * @param unit
 */

data class BaseMetrics(

    @Json(name = "units")
    val units: kotlin.Int? = null,

    @Json(name = "facet")
    val facet: BaseMetrics.Facet? = null,

    @Json(name = "unit_reference")
    val unitReference: kotlin.String? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null

) {

    /**
     *
     *
     * Values: countries,cities,devices,referrers,referrersByDomain,referringDomains,referringNetworks,shortenCounts
     */
    enum class Facet(val value: kotlin.String) {
        @Json(name = "countries") countries("countries"),
        @Json(name = "cities") cities("cities"),
        @Json(name = "devices") devices("devices"),
        @Json(name = "referrers") referrers("referrers"),
        @Json(name = "referrers_by_domain") referrersByDomain("referrers_by_domain"),
        @Json(name = "referring_domains") referringDomains("referring_domains"),
        @Json(name = "referring_networks") referringNetworks("referring_networks"),
        @Json(name = "shorten_counts") shortenCounts("shorten_counts");
    }
}
