/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param campaignGuid
 * @param bitlinkId
 */

data class BaseChannelBitlink(

    @Json(name = "campaign_guid")
    val campaignGuid: kotlin.String? = null,

    @Json(name = "bitlink_id")
    val bitlinkId: kotlin.String? = null

)
