/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param fieldAccountId
 * @param iframeId
 * @param tenantId
 * @param token
 * @param key
 * @param signature
 */

data class BillingSignature(

    @Json(name = "field_account_id")
    val fieldAccountId: kotlin.String? = null,

    @Json(name = "iframe_id")
    val iframeId: kotlin.String? = null,

    @Json(name = "tenant_id")
    val tenantId: kotlin.String? = null,

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "key")
    val key: kotlin.String? = null,

    @Json(name = "signature")
    val signature: kotlin.String? = null

)
