/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param billingAddress
 * @param billingContact
 */

data class BillingInfo(

    @Json(name = "billing_address")
    val billingAddress: BillingAddress? = null,

    @Json(name = "billing_contact")
    val billingContact: BillingContact? = null

)
