/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param subscriptionDiscounts
 * @param lastFourDigits
 * @param subscriptionPrice
 * @param billingInfo
 * @param accountId
 * @param endDate ISO timestamp
 * @param contactInfo
 * @param accountNum
 * @param cardType
 * @param companyName
 * @param subscriptionStatus
 * @param renewalDate ISO timestamp
 * @param taxId
 */

data class BillingAccount(

    @Json(name = "subscription_discounts")
    val subscriptionDiscounts: kotlin.collections.List<SubscriptionDiscount>? = null,

    @Json(name = "last_four_digits")
    val lastFourDigits: kotlin.String? = null,

    @Json(name = "subscription_price")
    val subscriptionPrice: java.math.BigDecimal? = null,

    @Json(name = "billing_info")
    val billingInfo: BillingInfo? = null,

    @Json(name = "account_id")
    val accountId: kotlin.String? = null,

    /* ISO timestamp */
    @Json(name = "end_date")
    val endDate: kotlin.String? = null,

    @Json(name = "contact_info")
    val contactInfo: ContactInfo? = null,

    @Json(name = "account_num")
    val accountNum: kotlin.String? = null,

    @Json(name = "card_type")
    val cardType: kotlin.String? = null,

    @Json(name = "company_name")
    val companyName: kotlin.String? = null,

    @Json(name = "subscription_status")
    val subscriptionStatus: kotlin.String? = null,

    /* ISO timestamp */
    @Json(name = "renewal_date")
    val renewalDate: kotlin.String? = null,

    @Json(name = "tax_id")
    val taxId: kotlin.String? = null

)
