/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param groupGuids
 * @param promoCode
 * @param tierName
 */

data class BillingDowngrade(

    @Json(name = "group_guids")
    val groupGuids: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "promo_code")
    val promoCode: kotlin.String? = null,

    @Json(name = "tier_name")
    val tierName: kotlin.String? = null

)
