/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param city
 * @param country
 * @param state
 * @param address1
 * @param address2
 * @param zipCode
 */

data class BillingAddress(

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null,

    @Json(name = "address_1")
    val address1: kotlin.String? = null,

    @Json(name = "address_2")
    val address2: kotlin.String? = null,

    @Json(name = "zip_code")
    val zipCode: kotlin.String? = null

)
