/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param totalCount
 * @param overrides
 */

data class BitlinkOverridesData(

    @Json(name = "total_count")
    val totalCount: kotlin.Int,

    @Json(name = "overrides")
    val overrides: kotlin.collections.List<BitlinkOverrides>

)
