/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param hash The backhalf of the underlying hash link
 * @param groupGuid
 * @param createdAt
 * @param isActive
 * @param longUrl
 * @param isDeleted
 * @param login
 * @param targetBitlinkId The domain and backhalf of the underlying hash link
 * @param id The domain and backhalf of the parent override
 * @param deactivatedAt
 */

data class BitlinkHistoryAllOf(

    /* The backhalf of the underlying hash link */
    @Json(name = "hash")
    val hash: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "is_deleted")
    val isDeleted: kotlin.Boolean? = null,

    @Json(name = "login")
    val login: kotlin.String? = null,

    /* The domain and backhalf of the underlying hash link */
    @Json(name = "target_bitlink_id")
    val targetBitlinkId: kotlin.String? = null,

    /* The domain and backhalf of the parent override */
    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "deactivated_at")
    val deactivatedAt: kotlin.String? = null

)
