/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param created
 * @param rules
 * @param groupGuid
 * @param modified
 * @param version
 * @param link The fully qualified URL to the Override which is the Bitly link to use. Ex: https://foo.com/bar
 * @param id
 */

data class BitlinkOverridesAllOf(

    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "rules")
    val rules: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    /* The fully qualified URL to the Override which is the Bitly link to use. Ex: https://foo.com/bar */
    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

)
