/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param headers
 * @param uploadUrl
 * @param bucket
 * @param filename
 */

data class BulkShortenUploadData(

    @Json(name = "headers")
    val headers: kotlin.Any,

    @Json(name = "upload_url")
    val uploadUrl: kotlin.String,

    @Json(name = "bucket")
    val bucket: kotlin.String,

    @Json(name = "filename")
    val filename: kotlin.String

)
