/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param status
 * @param name
 * @param created
 * @param groupGuid
 * @param reportUrl
 * @param uploadedBy
 * @param orgGuid
 */

data class BulkShortenUpload(

    @Json(name = "status")
    val status: BulkShortenUpload.Status,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "created")
    val created: kotlin.String,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String,

    @Json(name = "report_url")
    val reportUrl: kotlin.String,

    @Json(name = "uploaded_by")
    val uploadedBy: kotlin.String,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String

) {

    /**
     *
     *
     * Values: inProgress,success,partialSuccess,failure
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") inProgress("in_progress"),
        @Json(name = "success") success("success"),
        @Json(name = "partial_success") partialSuccess("partial_success"),
        @Json(name = "failure") failure("failure");
    }
}
