/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param linkSaveFailures
 * @param keywordFailures
 * @param results
 * @param successes
 * @param channelBitlinkFailures
 * @param csvFormatFailures
 */

data class BulkAddResponseData(

    @Json(name = "link_save_failures")
    val linkSaveFailures: kotlin.Int? = null,

    @Json(name = "keyword_failures")
    val keywordFailures: kotlin.Int? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "successes")
    val successes: kotlin.Int? = null,

    @Json(name = "channel_bitlink_failures")
    val channelBitlinkFailures: kotlin.Int? = null,

    @Json(name = "csv_format_failures")
    val csvFormatFailures: kotlin.Int? = null

)
