/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param filename
 * @param groupGuid
 * @param email
 * @param customDomain
 */

data class BulkShortenValidate(

    @Json(name = "filename")
    val filename: kotlin.String,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "custom_domain")
    val customDomain: kotlin.String? = null

)
