/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param action archive or edit_tags
 * @param removeTags
 * @param archive
 * @param links this is limited to 100 bitlink ids
 * @param addTags
 */

data class BulkUpdateRequest(

    /* archive or edit_tags */
    @Json(name = "action")
    val action: BulkUpdateRequest.Action,

    @Json(name = "remove_tags")
    val removeTags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "archive")
    val archive: kotlin.Boolean? = null,

    /* this is limited to 100 bitlink ids */
    @Json(name = "links")
    val links: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "add_tags")
    val addTags: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * archive or edit_tags
     *
     * Values: archive,editTags
     */
    enum class Action(val value: kotlin.String) {
        @Json(name = "archive") archive("archive"),
        @Json(name = "edit_tags") editTags("edit_tags");
    }
}
