/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param createdTs
 * @param description
 * @param brandGuid
 * @param campaignChannels
 * @param createdBy
 * @param modifiedTs
 * @param totalClicks
 * @param guid
 * @param name
 */

data class CampaignClicksData(

    @Json(name = "created_ts")
    val createdTs: kotlin.Int? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "brand_guid")
    val brandGuid: kotlin.String? = null,

    @Json(name = "campaign_channels")
    val campaignChannels: kotlin.collections.List<CampaignChannelClicks>? = null,

    @Json(name = "created_by")
    val createdBy: kotlin.String? = null,

    @Json(name = "modified_ts")
    val modifiedTs: kotlin.Int? = null,

    @Json(name = "total_clicks")
    val totalClicks: kotlin.Int? = null,

    @Json(name = "guid")
    val guid: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

)
