/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param successes
 * @param createBitlinkFailures
 * @param shortenFailures
 * @param results
 * @param otherLinkFailures
 */

data class CampaignAddBitlinkResponseData(

    @Json(name = "successes")
    val successes: kotlin.Int? = null,

    @Json(name = "create_bitlink_failures")
    val createBitlinkFailures: kotlin.Int? = null,

    @Json(name = "shorten_failures")
    val shortenFailures: kotlin.Int? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<AddBitlinkResult>? = null,

    @Json(name = "other_link_failures")
    val otherLinkFailures: kotlin.Int? = null

)
