/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param createdTs
 * @param channelGuid
 * @param totalClicks
 * @param channelName
 * @param campaignGuid
 * @param channelBitlinks
 * @param clicks
 */

data class CampaignChannelClicks(

    @Json(name = "created_ts")
    val createdTs: kotlin.Int? = null,

    @Json(name = "channel_guid")
    val channelGuid: kotlin.String? = null,

    @Json(name = "total_clicks")
    val totalClicks: kotlin.Int? = null,

    @Json(name = "channel_name")
    val channelName: kotlin.String? = null,

    @Json(name = "campaign_guid")
    val campaignGuid: kotlin.String? = null,

    @Json(name = "channel_bitlinks")
    val channelBitlinks: ChannelBitlinks? = null,

    @Json(name = "clicks")
    val clicks: kotlin.collections.List<CampaignClickData>? = null

)
