/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param url
 * @param addUtmParams
 * @param channelGuids
 */

data class CampaignAddBitlink(

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "add_utm_params")
    val addUtmParams: kotlin.Boolean? = null,

    @Json(name = "channel_guids")
    val channelGuids: kotlin.collections.List<kotlin.String>? = null

)
