/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param groupGuid
 * @param channelGuids
 * @param description
 * @param name
 */

data class CampaignModify(

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "channel_guids")
    val channelGuids: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

)
