/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param createdTs
 * @param bitlinkId
 * @param channelGuid
 * @param campaignGuid
 * @param keywordLink
 * @param title
 * @param campaignIds
 * @param totalClicks
 * @param link
 * @param clientId
 * @param longUrl
 * @param clicks
 */

data class ChannelBitlink(

    @Json(name = "created_ts")
    val createdTs: kotlin.Int,

    @Json(name = "bitlink_id")
    val bitlinkId: kotlin.String,

    @Json(name = "channel_guid")
    val channelGuid: kotlin.String,

    @Json(name = "campaign_guid")
    val campaignGuid: kotlin.String,

    @Json(name = "keyword_link")
    val keywordLink: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "campaign_ids")
    val campaignIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "total_clicks")
    val totalClicks: kotlin.Int? = null,

    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "client_id")
    val clientId: kotlin.String? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "clicks")
    val clicks: kotlin.collections.List<CampaignClickData>? = null

)
