/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param total
 * @param bitlinks
 */

data class ChannelBitlinks(

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "bitlinks")
    val bitlinks: kotlin.collections.List<ChannelBitlink>? = null

)
