/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param launchpadViews
 * @param otherMetrics
 */

data class CityViewMetricsAllOf(

    @Json(name = "launchpad_views")
    val launchpadViews: kotlin.collections.List<ViewMetric>? = null,

    @Json(name = "other_metrics")
    val otherMetrics: OtherViewMetrics? = null

)
