/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param units
 * @param unitReference
 * @param unit
 * @param linkClicks
 */

data class Clicks(

    @Json(name = "units")
    val units: kotlin.Int? = null,

    @Json(name = "unit_reference")
    val unitReference: kotlin.String? = null,

    @Json(name = "unit")
    val unit: Clicks.Unit? = null,

    @Json(name = "link_clicks")
    val linkClicks: kotlin.collections.List<LinkClicks>? = null

) {

    /**
     *
     *
     * Values: minute,hour,day,week,month
     */
    enum class Unit(val value: kotlin.String) {
        @Json(name = "minute") minute("minute"),
        @Json(name = "hour") hour("hour"),
        @Json(name = "day") day("day"),
        @Json(name = "week") week("week"),
        @Json(name = "month") month("month");
    }
}
