/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param clicks
 * @param id
 */

data class ClickLink(

    @Json(name = "clicks")
    val clicks: kotlin.Int? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

)
