/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param consumableFeatures
 */

data class ConsumableFeatures(

    @Json(name = "consumable_features")
    val consumableFeatures: kotlin.collections.List<ConsumableFeature>? = null

)
