/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param name
 * @param created ISO_TIMESTAMP
 * @param modified ISO_TIMESTAMP
 * @param limit
 * @param addOns
 * @param isTierDefault
 * @param id
 */

data class ConsumableFeature(

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "created")
    val created: kotlin.String? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "limit")
    val limit: kotlin.Int? = null,

    @Json(name = "add_ons")
    val addOns: kotlin.collections.List<ConsumableFeatureAddOn>? = null,

    @Json(name = "is_tier_default")
    val isTierDefault: kotlin.Boolean? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

)
