/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param count
 * @param name
 * @param created ISO_TIMESTAMP
 * @param isLimited
 * @param modified ISO_TIMESTAMP
 * @param limit
 * @param addOnUsage
 * @param isTierDefault
 * @param id
 * @param isEnforced
 */

data class ConsumableFeatureFull(

    @Json(name = "count")
    val count: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "is_limited")
    val isLimited: kotlin.Boolean? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "limit")
    val limit: kotlin.Int? = null,

    @Json(name = "add_on_usage")
    val addOnUsage: AddOnUsage? = null,

    @Json(name = "is_tier_default")
    val isTierDefault: kotlin.Boolean? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "is_enforced")
    val isEnforced: kotlin.Boolean? = null

)
