/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param endDate ISO_TIMESTAMP
 * @param created ISO_TIMESTAMP
 * @param isActive
 * @param modified ISO_TIMESTAMP
 * @param featureName
 * @param startDate ISO_TIMESTAMP
 * @param quantity
 */

data class ConsumableFeatureAddOn(

    /* ISO_TIMESTAMP */
    @Json(name = "end_date")
    val endDate: kotlin.String? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "feature_name")
    val featureName: kotlin.String? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "start_date")
    val startDate: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Int? = null

)
