/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param rules
 * @param groupGuid
 */

data class CreateOverrideRules(

    @Json(name = "rules")
    val rules: kotlin.String,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null

)
