/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param groupGuid
 * @param domain
 * @param keyword
 */

data class CreateLaunchpad(

    @Json(name = "group_guid")
    val groupGuid: kotlin.String,

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "keyword")
    val keyword: kotlin.String

)
