/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param text
 * @param bitlink
 * @param accountType
 * @param accountId
 * @param groupGuid
 */

data class CreateShare(

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "bitlink")
    val bitlink: kotlin.String? = null,

    @Json(name = "account_type")
    val accountType: SocialAccounts? = null,

    @Json(name = "account_id")
    val accountId: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null

)
