/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param hash
 * @param uuid
 * @param keyword
 * @param created
 * @param groupGuid
 * @param firstCreated
 * @param isActive
 * @param longUrl
 * @param deactivated
 * @param bsd
 * @param login
 */

data class CustomBitlinkHistory(

    @Json(name = "hash")
    val hash: kotlin.String? = null,

    @Json(name = "uuid")
    val uuid: kotlin.String? = null,

    @Json(name = "keyword")
    val keyword: kotlin.String? = null,

    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "first_created")
    val firstCreated: kotlin.String? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "deactivated")
    val deactivated: kotlin.String? = null,

    @Json(name = "bsd")
    val bsd: kotlin.String? = null,

    @Json(name = "login")
    val login: kotlin.String? = null

)
