/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * information about given custom domain
 *
 * @param deeplinkApps
 * @param hstsEnabled
 * @param upgradeInsecureRequests
 * @param customDomain
 * @param validationError
 * @param created
 * @param isActive
 * @param rootRedirect
 * @param sslConfigurationError
 * @param sslAutoconfigureError
 * @param groupGuids
 * @param sslCert
 * @param wildcardRedirect
 * @param configurationLastCheckTs
 * @param httpsEnabled
 * @param validationStatus
 * @param httpsBitlinks
 */

data class CustomDomainBody(

    @Json(name = "deeplink_apps")
    val deeplinkApps: kotlin.collections.List<MinimalDeeplinkApp>? = null,

    @Json(name = "hsts_enabled")
    val hstsEnabled: kotlin.Boolean? = null,

    @Json(name = "upgrade_insecure_requests")
    val upgradeInsecureRequests: kotlin.Boolean? = null,

    @Json(name = "custom_domain")
    val customDomain: kotlin.String? = null,

    @Json(name = "validation_error")
    val validationError: kotlin.String? = null,

    @Json(name = "created")
    val created: kotlin.Int? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "root_redirect")
    val rootRedirect: kotlin.String? = null,

    @Json(name = "ssl_configuration_error")
    val sslConfigurationError: kotlin.String? = null,

    @Json(name = "ssl_autoconfigure_error")
    val sslAutoconfigureError: kotlin.Boolean? = null,

    @Json(name = "group_guids")
    val groupGuids: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "ssl_cert")
    val sslCert: PublicSSLCert? = null,

    @Json(name = "wildcard_redirect")
    val wildcardRedirect: kotlin.String? = null,

    @Json(name = "configuration_last_check_ts")
    val configurationLastCheckTs: kotlin.String? = null,

    @Json(name = "https_enabled")
    val httpsEnabled: kotlin.Boolean? = null,

    @Json(name = "validation_status")
    val validationStatus: CustomDomainBody.ValidationStatus? = null,

    @Json(name = "https_bitlinks")
    val httpsBitlinks: kotlin.Boolean? = null

) {

    /**
     *
     *
     * Values: ok,pending,error
     */
    enum class ValidationStatus(val value: kotlin.String) {
        @Json(name = "ok") ok("ok"),
        @Json(name = "pending") pending("pending"),
        @Json(name = "error") error("error");
    }
}
