/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param bitlink
 * @param bitlinkHistory
 * @param customBitlink
 */

data class CustomBitlink(

    @Json(name = "bitlink")
    val bitlink: BitlinkBody? = null,

    @Json(name = "bitlink_history")
    val bitlinkHistory: kotlin.collections.List<CustomBitlinkHistory>? = null,

    @Json(name = "custom_bitlink")
    val customBitlink: kotlin.String? = null

)
