/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param archived
 * @param unitReference
 * @param linkDeeplinks
 * @param tags
 * @param campaignIds
 * @param modifiedAfter
 * @param keyword
 * @param createdAfter
 * @param customBitlink
 * @param units
 * @param query
 * @param reportType
 * @param createdBefore
 * @param emails
 * @param unit
 */

data class DataExportQuery(

    @Json(name = "archived")
    val archived: kotlin.String? = null,

    @Json(name = "unit_reference")
    val unitReference: kotlin.Int? = null,

    @Json(name = "link_deeplinks")
    val linkDeeplinks: kotlin.String? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "campaign_ids")
    val campaignIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "modified_after")
    val modifiedAfter: kotlin.Int? = null,

    @Json(name = "keyword")
    val keyword: kotlin.String? = null,

    @Json(name = "created_after")
    val createdAfter: kotlin.Int? = null,

    @Json(name = "custom_bitlink")
    val customBitlink: kotlin.String? = null,

    @Json(name = "units")
    val units: kotlin.Int? = null,

    @Json(name = "query")
    val query: kotlin.String? = null,

    @Json(name = "report_type")
    val reportType: kotlin.String? = null,

    @Json(name = "created_before")
    val createdBefore: kotlin.Int? = null,

    @Json(name = "emails")
    val emails: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null

)
