/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param selection
 * @param optionalText
 */

data class DeactivateUserFeedback(

    @Json(name = "selection")
    val selection: kotlin.String? = null,

    @Json(name = "optional_text")
    val optionalText: kotlin.String? = null

)
