/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param feedback
 * @param confirmText
 */

data class DeactivateUser(

    @Json(name = "feedback")
    val feedback: DeactivateUserFeedback? = null,

    @Json(name = "confirm_text")
    val confirmText: kotlin.String? = null

)
