/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param appInstalls
 * @param storeVisits
 * @param interstitalViews
 * @param appOpens
 * @param webOpens
 */

data class DeeplinkMetric(

    @Json(name = "app_installs")
    val appInstalls: kotlin.Int? = null,

    @Json(name = "store_visits")
    val storeVisits: kotlin.Int? = null,

    @Json(name = "interstital_views")
    val interstitalViews: kotlin.Int? = null,

    @Json(name = "app_opens")
    val appOpens: kotlin.Int? = null,

    @Json(name = "web_opens")
    val webOpens: kotlin.Int? = null

)
