/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param thirdPartyAppId
 * @param installUrl
 * @param name
 * @param os
 * @param createdTs
 * @param scheme
 * @param legacyAppId
 * @param iconUrl
 * @param organizationGuid
 * @param modifiedTs
 * @param guid
 * @param appleAppEntitlementId
 * @param androidSha256
 */

data class DeeplinkApp(

    @Json(name = "third_party_app_id")
    val thirdPartyAppId: kotlin.String,

    @Json(name = "install_url")
    val installUrl: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "os")
    val os: DeeplinkApp.Os,

    @Json(name = "created_ts")
    val createdTs: kotlin.Int? = null,

    @Json(name = "scheme")
    val scheme: kotlin.String? = null,

    @Json(name = "legacy_app_id")
    val legacyAppId: kotlin.String? = null,

    @Json(name = "icon_url")
    val iconUrl: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null,

    @Json(name = "modified_ts")
    val modifiedTs: kotlin.Int? = null,

    @Json(name = "guid")
    val guid: kotlin.String? = null,

    @Json(name = "apple_app_entitlement_id")
    val appleAppEntitlementId: kotlin.String? = null,

    @Json(name = "android_sha256")
    val androidSha256: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     *
     *
     * Values: ios,android
     */
    enum class Os(val value: kotlin.String) {
        @Json(name = "ios") ios("ios"),
        @Json(name = "android") android("android");
    }
}
