/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param unitReference data returned up to this reference timestamp
 * @param ios
 * @param other
 * @param units the number of units queried for
 * @param android
 * @param unit
 */

data class DeeplinkMetricsRollup(

    /* data returned up to this reference timestamp */
    @Json(name = "unit_reference")
    val unitReference: kotlin.String? = null,

    @Json(name = "ios")
    val ios: DeeplinkMetric? = null,

    @Json(name = "other")
    val other: DeeplinkMetric? = null,

    /* the number of units queried for */
    @Json(name = "units")
    val units: kotlin.Int? = -1,

    @Json(name = "android")
    val android: DeeplinkMetric? = null,

    @Json(name = "unit")
    val unit: TimeUnit? = TimeUnit.day

)
