/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param appUriPath
 * @param installType
 * @param installUrl
 * @param appId
 */

data class Deeplink(

    @Json(name = "app_uri_path")
    val appUriPath: kotlin.String? = null,

    @Json(name = "install_type")
    val installType: kotlin.String? = null,

    @Json(name = "install_url")
    val installUrl: kotlin.String? = null,

    @Json(name = "app_id")
    val appId: kotlin.String? = null

)
