/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * update custom domain fields
 *
 * @param httpsEnabled
 * @param hstsEnabled
 * @param upgradeInsecureRequests
 * @param wildcardRedirect
 * @param rootRedirect
 */

data class DomainUpdate(

    @Json(name = "https_enabled")
    val httpsEnabled: kotlin.Boolean? = null,

    @Json(name = "hsts_enabled")
    val hstsEnabled: kotlin.Boolean? = null,

    @Json(name = "upgrade_insecure_requests")
    val upgradeInsecureRequests: kotlin.Boolean? = null,

    @Json(name = "wildcard_redirect")
    val wildcardRedirect: kotlin.String? = null,

    @Json(name = "root_redirect")
    val rootRedirect: kotlin.String? = null

)
