/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param status processing status of the domain
 * @param domain name of the requested domain
 * @param renewDeadline date the domain must renew by
 * @param expires when the domain will expire
 * @param renewAuto whether the domain is configured to automatically renew
 * @param expirationProtected whether the domain is protected from expiration
 */

data class DomainRegistrarInfo(

    /* processing status of the domain */
    @Json(name = "status")
    val status: kotlin.String? = null,

    /* name of the requested domain */
    @Json(name = "domain")
    val domain: kotlin.String? = null,

    /* date the domain must renew by */
    @Json(name = "renew_deadline")
    val renewDeadline: kotlin.String? = null,

    /* when the domain will expire */
    @Json(name = "expires")
    val expires: kotlin.String? = null,

    /* whether the domain is configured to automatically renew */
    @Json(name = "renew_auto")
    val renewAuto: kotlin.Boolean? = null,

    /* whether the domain is protected from expiration */
    @Json(name = "expiration_protected")
    val expirationProtected: kotlin.Boolean? = null

)
