/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param content
 * @param url
 * @param agreementKey
 * @param title
 */

data class DomainAgreement(

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "agreement_key")
    val agreementKey: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null

)
