/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param orgGuid
 * @param accountNum
 * @param termEndDate
 */

data class DowngradeOrgBody(

    @Json(name = "org_guid")
    val orgGuid: kotlin.String? = null,

    @Json(name = "account_num")
    val accountNum: kotlin.String? = null,

    @Json(name = "term_end_date")
    val termEndDate: kotlin.String? = null

)
