/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isPrimary
 * @param isVerified
 * @param email
 */

data class Email(

    @Json(name = "is_primary")
    val isPrimary: kotlin.Boolean? = null,

    @Json(name = "is_verified")
    val isVerified: kotlin.Boolean? = null,

    @Json(name = "email")
    val email: kotlin.String? = null

)
