/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param uiAction
 * @param referrer
 * @param action
 * @param initiatedBy
 * @param uiActionDate
 * @param login
 * @param orgGuid
 * @param groupGuid
 */

data class Event(

    @Json(name = "ui_action")
    val uiAction: kotlin.String,

    @Json(name = "referrer")
    val referrer: kotlin.String,

    @Json(name = "action")
    val action: kotlin.String,

    @Json(name = "initiated_by")
    val initiatedBy: Event.InitiatedBy,

    @Json(name = "ui_action_date")
    val uiActionDate: kotlin.String,

    @Json(name = "login")
    val login: kotlin.String,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null

) {

    /**
     *
     *
     * Values: app,user
     */
    enum class InitiatedBy(val value: kotlin.String) {
        @Json(name = "app") app("app"),
        @Json(name = "user") user("user");
    }
}
