/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param longUrl
 * @param createdAt
 * @param link
 * @param id
 */

data class ExpandedBitlink(

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

)
