/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param count
 * @param `value`
 */

data class FacetCountItem(

    @Json(name = "count")
    val count: kotlin.Int? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null

)
