/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param totalCount
 * @param ts
 * @param items
 */

data class FacetCountData(

    @Json(name = "total_count")
    val totalCount: kotlin.Int? = null,

    @Json(name = "ts")
    val ts: kotlin.Int? = null,

    @Json(name = "items")
    val items: kotlin.collections.List<FacetCountItem>? = null

)
