/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param consumableFeatures an array of all of the organizations consumable features
 * @param accessFeatures an array of all of the organizations access features
 */

data class FeatureUsage(

    /* an array of all of the organizations consumable features */
    @Json(name = "consumable_features")
    val consumableFeatures: kotlin.collections.List<ConsumableFeatureFull>,

    /* an array of all of the organizations access features */
    @Json(name = "access_features")
    val accessFeatures: kotlin.collections.List<AccessFeature>

)
