/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param fieldType
 * @param name
 * @param required
 * @param label
 * @param config
 * @param response
 */

data class FormField(

    @Json(name = "field_type")
    val fieldType: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "required")
    val required: kotlin.Boolean? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "config")
    val config: FormConfig? = null,

    @Json(name = "response")
    val response: kotlin.String? = null

)
