/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param submitText
 * @param name
 * @param responseStatus
 * @param pages
 * @param version
 * @param groupGuid
 * @param login
 * @param skipText
 * @param orgGuid
 */

data class FormCapturePayload(

    @Json(name = "submit_text")
    val submitText: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "response_status")
    val responseStatus: kotlin.String? = null,

    @Json(name = "pages")
    val pages: kotlin.collections.List<FormPage>? = null,

    @Json(name = "version")
    val version: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "login")
    val login: kotlin.String? = null,

    @Json(name = "skip_text")
    val skipText: kotlin.String? = null,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String? = null

)
