/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param display
 * @param key
 */

data class FormSelectOptions(

    @Json(name = "display")
    val display: kotlin.String? = null,

    @Json(name = "key")
    val key: kotlin.String? = null

)
