/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isCustomized
 * @param created
 * @param groupGuid
 * @param title
 * @param modified
 * @param longUrl
 * @param customization
 * @param link
 * @param isHidden
 * @param qrUri Data URI of QR Code image
 * @param id
 * @param scans
 */

data class FullQRCodeWithScans(

    @Json(name = "is_customized")
    val isCustomized: kotlin.Boolean? = null,

    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "customization")
    val customization: QRCustomizations? = null,

    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "is_hidden")
    val isHidden: kotlin.Boolean? = null,

    /* Data URI of QR Code image */
    @Json(name = "qr_uri")
    val qrUri: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "scans")
    val scans: kotlin.Int? = null

)
