/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param longUrl
 * @param domain
 * @param title
 * @param groupGuid Always include a specific group and custom domain in your shorten calls.
 * @param tags
 * @param deeplinks
 */

data class FullShorten(

    @Json(name = "long_url")
    val longUrl: kotlin.String,

    @Json(name = "domain")
    val domain: kotlin.String? = "bit.ly",

    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Always include a specific group and custom domain in your shorten calls. */
    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "deeplinks")
    val deeplinks: kotlin.collections.List<Deeplink>? = null

)
