/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param hasStored
 * @param isCustomized
 * @param created
 * @param groupGuid
 * @param qrCode Data URI of QR Code image
 * @param modified
 * @param link
 * @param customization
 * @param isHidden
 * @param logoImageUrl Public URL of QR Code logo
 * @param id
 */

data class FullQRCode(

    @Json(name = "has_stored")
    val hasStored: kotlin.Boolean? = null,

    @Json(name = "is_customized")
    val isCustomized: kotlin.Boolean? = null,

    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    /* Data URI of QR Code image */
    @Json(name = "qr_code")
    val qrCode: kotlin.String? = null,

    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "customization")
    val customization: QRCustomizations? = null,

    @Json(name = "is_hidden")
    val isHidden: kotlin.Boolean? = null,

    /* Public URL of QR Code logo */
    @Json(name = "logo_image_url")
    val logoImageUrl: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

)
