/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param accessToken
 * @param isNewToken
 */

data class GenericAccessToken(

    @Json(name = "access_token")
    val accessToken: kotlin.String,

    @Json(name = "is_new_token")
    val isNewToken: kotlin.Boolean

)
