/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param groupGuid
 * @param domainPreference
 */

data class GroupPreferences(

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "domain_preference")
    val domainPreference: kotlin.String? = null

)
