/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param bsds
 * @param name
 * @param organizationGuid
 */

data class GroupUpdate(

    @Json(name = "bsds")
    val bsds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null

)
