/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param groupGuid
 * @param image
 * @param use
 * @param crop
 */

data class ImageUpload(

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "image")
    val image: java.io.File? = null,

    @Json(name = "use")
    val use: ImageUpload.Use? = null,

    @Json(name = "crop")
    val crop: kotlin.String? = null

) {

    /**
     *
     *
     * Values: `null`,defaultQrCodeImage
     */
    enum class Use(val value: kotlin.String) {
        @Json(name = "null") `null`("null"),
        @Json(name = "default_qr_code_image") defaultQrCodeImage("default_qr_code_image");
    }
}
