/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param max
 * @param min
 */

data class ImageCrop(

    @Json(name = "max")
    val max: ImageCropPoint? = null,

    @Json(name = "min")
    val min: ImageCropPoint? = null

)
