/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param imageUrl
 * @param imageGuid
 */

data class ImageUploadResponse(

    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    @Json(name = "image_guid")
    val imageGuid: kotlin.String? = null

)
