/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * Values: noInstall,autoInstall,promoteInstall
 */

enum class InstallPreference(val value: kotlin.String) {

    @Json(name = "no_install")
    noInstall("no_install"),

    @Json(name = "auto_install")
    autoInstall("auto_install"),

    @Json(name = "promote_install")
    promoteInstall("promote_install");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InstallPreference) "$data" else null

        /**
         * Returns a valid [InstallPreference] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InstallPreference? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}
