/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param interventionDate
 * @param interventionsOffered
 * @param interventionAction
 * @param orgGuid
 * @param guid
 * @param login
 */

data class Intervention(

    @Json(name = "intervention_date")
    val interventionDate: kotlin.String? = null,

    @Json(name = "interventions_offered")
    val interventionsOffered: kotlin.collections.List<InterventionsOffered>? = null,

    @Json(name = "intervention_action")
    val interventionAction: kotlin.String? = null,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String? = null,

    @Json(name = "guid")
    val guid: kotlin.String? = null,

    @Json(name = "login")
    val login: kotlin.String? = null

)
