/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param roleName
 * @param email
 * @param groups
 * @param created
 */

data class Invitation(

    @Json(name = "role_name")
    val roleName: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "groups")
    val groups: kotlin.collections.List<InvitationGroup>? = null,

    @Json(name = "created")
    val created: kotlin.String? = null

)
