/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param invitedOrgName
 * @param invitedOrgGuid
 * @param token
 * @param invitedByEmail
 * @param invitedBy
 */

data class InvitationForLogin(

    @Json(name = "invited_org_name")
    val invitedOrgName: kotlin.String,

    @Json(name = "invited_org_guid")
    val invitedOrgGuid: kotlin.String,

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "invited_by_email")
    val invitedByEmail: kotlin.String,

    @Json(name = "invited_by")
    val invitedBy: kotlin.String

)
