/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isActive
 * @param launchpadId
 * @param bitlink
 * @param buttonId
 * @param keyword
 * @param title
 * @param isPinned
 * @param domain
 * @param scheduleEnd
 * @param sortOrder
 * @param longUrl
 * @param scheme
 * @param scheduleStart
 */

data class LaunchpadButton(

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "launchpad_id")
    val launchpadId: kotlin.String? = null,

    @Json(name = "bitlink")
    val bitlink: kotlin.String? = null,

    @Json(name = "button_id")
    val buttonId: kotlin.String? = null,

    @Json(name = "keyword")
    val keyword: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "is_pinned")
    val isPinned: kotlin.Boolean? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "schedule_end")
    val scheduleEnd: kotlin.String? = null,

    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "scheme")
    val scheme: kotlin.String? = null,

    @Json(name = "schedule_start")
    val scheduleStart: kotlin.String? = null

)
