/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param url
 * @param channel
 */

data class LaunchpadContentSocial(

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "channel")
    val channel: kotlin.String? = null

)
