/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param unitReference
 * @param linkClicks
 * @param performanceStart
 * @param performanceEnd
 * @param units
 * @param unit
 */

data class LaunchpadLinkPerformance(

    @Json(name = "unit_reference")
    val unitReference: kotlin.String? = null,

    @Json(name = "link_clicks")
    val linkClicks: kotlin.collections.List<LaunchpadClicks>? = null,

    @Json(name = "performance_start")
    val performanceStart: kotlin.String? = null,

    @Json(name = "performance_end")
    val performanceEnd: kotlin.String? = null,

    @Json(name = "units")
    val units: kotlin.Int? = null,

    @Json(name = "unit")
    val unit: LaunchpadLinkPerformance.Unit? = null

) {

    /**
     *
     *
     * Values: minute,hour,day,week,month
     */
    enum class Unit(val value: kotlin.String) {
        @Json(name = "minute") minute("minute"),
        @Json(name = "hour") hour("hour"),
        @Json(name = "day") day("day"),
        @Json(name = "week") week("week"),
        @Json(name = "month") month("month");
    }
}
