/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isActive
 * @param launchpadId
 * @param buttonId
 * @param type
 * @param scheduleEnd
 * @param content
 * @param sortOrder
 * @param scheduleStart
 */

data class LaunchpadSocial(

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "launchpad_id")
    val launchpadId: kotlin.String? = null,

    @Json(name = "button_id")
    val buttonId: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "schedule_end")
    val scheduleEnd: kotlin.String? = null,

    @Json(name = "content")
    val content: LaunchpadContentSocial? = null,

    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    @Json(name = "schedule_start")
    val scheduleStart: kotlin.String? = null

)
