/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param bitlink
 * @param title
 * @param isActive
 * @param isPinned
 * @param scheduleEnd
 * @param content
 * @param longUrl
 * @param domain
 * @param scheduleStart
 */

data class LaunchpadButtonRequest(

    @Json(name = "bitlink")
    val bitlink: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "is_pinned")
    val isPinned: kotlin.Boolean? = null,

    @Json(name = "schedule_end")
    val scheduleEnd: kotlin.String? = null,

    @Json(name = "content")
    val content: ContentRequestBitlink? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "schedule_start")
    val scheduleStart: kotlin.String? = null

)
