/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isActive
 * @param launchpadId
 * @param isEdited
 * @param domain
 * @param keyword
 * @param socials
 * @param draftId
 * @param buttons
 * @param launchpadAppearance
 * @param images
 * @param scheme
 */

data class Launchpad(

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "launchpad_id")
    val launchpadId: kotlin.String? = null,

    @Json(name = "is_edited")
    val isEdited: kotlin.Boolean? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "keyword")
    val keyword: kotlin.String? = null,

    @Json(name = "socials")
    val socials: kotlin.collections.List<LaunchpadSocial>? = null,

    @Json(name = "draft_id")
    val draftId: kotlin.String? = null,

    @Json(name = "buttons")
    val buttons: kotlin.collections.List<LaunchpadButton>? = null,

    @Json(name = "launchpad_appearance")
    val launchpadAppearance: LaunchpadAppearance? = null,

    @Json(name = "images")
    val images: LaunchpadImages? = null,

    @Json(name = "scheme")
    val scheme: kotlin.String? = null

)
