/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param url
 * @param imageUse
 * @param crop
 * @param imageGuid
 */

data class LaunchpadImage(

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "image_use")
    val imageUse: kotlin.String? = null,

    @Json(name = "crop")
    val crop: kotlin.String? = null,

    @Json(name = "image_guid")
    val imageGuid: kotlin.String? = null

)
