/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param shape
 * @param buttonTextColor
 * @param shadow
 * @param buttonBackground
 */

data class LaunchpadButtonAppearance(

    @Json(name = "shape")
    val shape: kotlin.Int? = null,

    @Json(name = "button_text_color")
    val buttonTextColor: kotlin.String? = null,

    @Json(name = "shadow")
    val shadow: kotlin.Int? = null,

    @Json(name = "button_background")
    val buttonBackground: kotlin.String? = null

)
