/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param bitlink
 * @param isPinned
 * @param title
 */

data class LaunchpadContentBitlinkRequestContent(

    @Json(name = "bitlink")
    val bitlink: kotlin.String? = null,

    @Json(name = "is_pinned")
    val isPinned: kotlin.Boolean? = null,

    @Json(name = "title")
    val title: kotlin.String? = null

)
