/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param launchpadId
 * @param qrCode
 * @param link
 */

data class LaunchpadQRCode(

    @Json(name = "launchpad_id")
    val launchpadId: kotlin.String? = null,

    @Json(name = "qr_code")
    val qrCode: kotlin.String? = null,

    @Json(name = "link")
    val link: kotlin.String? = null

)
