/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param domain
 * @param bitlinkId
 * @param keyword
 * @param title
 * @param isActive
 * @param longUrl
 * @param date
 * @param clicks
 */

data class LaunchpadClicks(

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "bitlink_id")
    val bitlinkId: kotlin.String? = null,

    @Json(name = "keyword")
    val keyword: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "long_url")
    val longUrl: kotlin.String? = null,

    @Json(name = "date")
    val date: kotlin.String? = null,

    @Json(name = "clicks")
    val clicks: kotlin.Int? = null

)
