/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param `value`
 * @param key
 */

data class Metric(

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "key")
    val key: kotlin.String? = null

)
