/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * Deep Linking object
 *
 * @param guid
 * @param os
 */

data class MinimalDeeplinkApp(

    @Json(name = "guid")
    val guid: kotlin.String? = null,

    @Json(name = "os")
    val os: kotlin.String? = null

)
