/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param ownerLogin
 * @param link
 * @param name
 * @param clientId
 * @param description
 */

data class OAuthAppWithOwnerLogin(

    @Json(name = "owner_login")
    val ownerLogin: kotlin.String? = null,

    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "client_id")
    val clientId: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

)
