/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param name
 * @param bsds
 * @param created
 * @param isActive
 * @param modified
 * @param tierDisplayName
 * @param tierFamily
 * @param tier
 * @param role
 * @param guid
 * @param references
 */

data class Organization(

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "bsds")
    val bsds: kotlin.collections.List<kotlin.String>,

    @Json(name = "created")
    val created: kotlin.String,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "modified")
    val modified: kotlin.String,

    @Json(name = "tier_display_name")
    val tierDisplayName: kotlin.String,

    @Json(name = "tier_family")
    val tierFamily: kotlin.String,

    @Json(name = "tier")
    val tier: kotlin.String,

    @Json(name = "role")
    val role: kotlin.String,

    @Json(name = "guid")
    val guid: kotlin.String,

    @Json(name = "references")
    val references: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

)
