/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * an array of org emails
 *
 * @param emails
 */

data class OrgEmails(

    @Json(name = "emails")
    val emails: kotlin.collections.List<OrgEmail>? = null

)
