/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param login
 * @param orgGuid
 * @param email
 */

data class OrgEmailBody(

    @Json(name = "login")
    val login: kotlin.String? = null,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null

)
