/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param status
 * @param created ISO timestamp
 * @param deactivated ISO timestamp
 * @param tierChangeDate ISO timestamp
 * @param activated ISO timestamp
 * @param modified ISO timestamp
 * @param tierName
 * @param orgGuid
 */

data class OrgTierHistory(

    @Json(name = "status")
    val status: kotlin.String,

    /* ISO timestamp */
    @Json(name = "created")
    val created: kotlin.String,

    /* ISO timestamp */
    @Json(name = "deactivated")
    val deactivated: kotlin.String,

    /* ISO timestamp */
    @Json(name = "tier_change_date")
    val tierChangeDate: kotlin.String,

    /* ISO timestamp */
    @Json(name = "activated")
    val activated: kotlin.String,

    /* ISO timestamp */
    @Json(name = "modified")
    val modified: kotlin.String,

    @Json(name = "tier_name")
    val tierName: kotlin.String,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String

)
