/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param otherCityViews
 * @param noCityViews
 */

data class OtherViewMetrics(

    @Json(name = "other_city_views")
    val otherCityViews: kotlin.Int? = null,

    @Json(name = "no_city_views")
    val noCityViews: kotlin.Int? = null

)
