/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param otherCityClicks
 * @param noCityClicks
 */

data class OtherMetrics(

    @Json(name = "other_city_clicks")
    val otherCityClicks: kotlin.Int? = null,

    @Json(name = "no_city_clicks")
    val noCityClicks: kotlin.Int? = null

)
