/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param subscriptionDiscounts
 * @param invoiceSummary
 * @param billingAccount
 */

data class PaymentInvoiceDetail(

    @Json(name = "subscription_discounts")
    val subscriptionDiscounts: kotlin.collections.List<SubscriptionDiscount>? = null,

    @Json(name = "invoice_summary")
    val invoiceSummary: PaymentInvoice? = null,

    @Json(name = "billing_account")
    val billingAccount: BillingAccount? = null

)
