/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param paymentInvoices
 */

data class PaymentInvoices(

    @Json(name = "payment_invoices")
    val paymentInvoices: kotlin.collections.List<PaymentInvoice>? = null

)
