/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param totalTax
 * @param description
 * @param charges
 * @param invoiceId
 * @param invoiceDate
 * @param payments
 * @param invoiceNumber
 * @param total
 * @param subtotal
 * @param invoiceDueDate
 */

data class PaymentInvoice(

    @Json(name = "total_tax")
    val totalTax: java.math.BigDecimal? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "charges")
    val charges: Charges? = null,

    @Json(name = "invoice_id")
    val invoiceId: kotlin.String? = null,

    @Json(name = "invoice_date")
    val invoiceDate: kotlin.String? = null,

    @Json(name = "payments")
    val payments: kotlin.collections.List<Payments>? = null,

    @Json(name = "invoice_number")
    val invoiceNumber: kotlin.String? = null,

    @Json(name = "total")
    val total: java.math.BigDecimal? = null,

    @Json(name = "subtotal")
    val subtotal: java.math.BigDecimal? = null,

    @Json(name = "invoice_due_date")
    val invoiceDueDate: kotlin.String? = null

)
