/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param paymentNumber
 * @param paymentDate
 * @param paymentAmount
 */

data class Payments(

    @Json(name = "payment_number")
    val paymentNumber: kotlin.String? = null,

    @Json(name = "payment_date")
    val paymentDate: kotlin.String? = null,

    @Json(name = "payment_amount")
    val paymentAmount: java.math.BigDecimal? = null

)
