/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param organizationGuid
 * @param planLimits
 */

data class PlanLimitsAllOf(

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null,

    @Json(name = "plan_limits")
    val planLimits: kotlin.collections.List<PlanLimit>? = null

)
