/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param endpoint
 * @param methods
 */

data class PlatformLimit(

    @Json(name = "endpoint")
    val endpoint: kotlin.String? = null,

    @Json(name = "methods")
    val methods: kotlin.collections.List<MethodLimit>? = null

)
