/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param promoCode
 * @param validPlans
 * @param discountAmount
 * @param discountType
 * @param numPeriodsToApplyDiscountType
 * @param numPeriodsToApplyDiscount
 * @param isValid
 */

data class PromoCode(

    @Json(name = "promo_code")
    val promoCode: kotlin.String? = null,

    @Json(name = "valid_plans")
    val validPlans: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "discount_amount")
    val discountAmount: java.math.BigDecimal? = null,

    @Json(name = "discount_type")
    val discountType: PromoCode.DiscountType? = null,

    @Json(name = "num_periods_to_apply_discount_type")
    val numPeriodsToApplyDiscountType: PromoCode.NumPeriodsToApplyDiscountType? = null,

    @Json(name = "num_periods_to_apply_discount")
    val numPeriodsToApplyDiscount: kotlin.Int? = null,

    @Json(name = "is_valid")
    val isValid: kotlin.Boolean? = null

) {

    /**
     *
     *
     * Values: fixedAmount,percent
     */
    enum class DiscountType(val value: kotlin.String) {
        @Json(name = "fixedAmount") fixedAmount("fixedAmount"),
        @Json(name = "percent") percent("percent");
    }
    /**
     *
     *
     * Values: month,annual
     */
    enum class NumPeriodsToApplyDiscountType(val value: kotlin.String) {
        @Json(name = "month") month("month"),
        @Json(name = "annual") annual("annual");
    }
}
