/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * Info needed for domain validation
 *
 * @param customDomain
 * @param organizationGuid
 */

data class PublicValidate(

    @Json(name = "custom_domain")
    val customDomain: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null

)
