/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * SSL Certification
 *
 * @param customCert
 * @param validEnd
 * @param issuer
 */

data class PublicSSLCert(

    @Json(name = "custom_cert")
    val customCert: kotlin.Boolean? = null,

    @Json(name = "valid_end")
    val validEnd: kotlin.String? = null,

    @Json(name = "issuer")
    val issuer: kotlin.String? = null

)
