/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param qrCode Data URI of QR Code image
 * @param link
 * @param id
 */

data class PublicQRCode(

    /* Data URI of QR Code image */
    @Json(name = "qr_code")
    val qrCode: kotlin.String? = null,

    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

)
