/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param domain
 * @param agreedAt ISO_TIMESTAMP
 * @param organizationGuid
 * @param agreementKeys
 */

data class PurchaseBSD(

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    /* ISO_TIMESTAMP */
    @Json(name = "agreed_at")
    val agreedAt: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null,

    @Json(name = "agreement_keys")
    val agreementKeys: kotlin.collections.List<kotlin.String>? = null

)
