/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param orderId
 * @param domain
 * @param total
 * @param organizationGuid
 */

data class PurchaseBSDResponse(

    @Json(name = "order_id")
    val orderId: kotlin.Int? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "total")
    val total: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null

)
