/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param qrCodes
 * @param total
 * @param page
 * @param propertySize
 */

data class QRCodes(

    @Json(name = "qr_codes")
    val qrCodes: kotlin.collections.List<FullQRCodeWithScans>? = null,

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "page")
    val page: kotlin.Int? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null

)
