/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param color A color denoted in hexadecimal format ei. \"1133ff\"
 * @param logoImageGuid Logo must first be uploaded through Bitly's QR Code Modal located on the \"All links\" page. Once created, a call to \"Retrieve a QR Code\" with specified bitlink will return the auto-generated \"logo_image_guid\"
 * @param imageFormat Determines the image format of the returned QR code
 * @param excludeBitlyLogo Removes the Bitly logo from the center of the generated QR image
 */

data class QRCustomizations(

    /* A color denoted in hexadecimal format ei. \"1133ff\" */
    @Json(name = "color")
    val color: kotlin.String? = null,

    /* Logo must first be uploaded through Bitly's QR Code Modal located on the \"All links\" page. Once created, a call to \"Retrieve a QR Code\" with specified bitlink will return the auto-generated \"logo_image_guid\" */
    @Json(name = "logo_image_guid")
    val logoImageGuid: kotlin.String? = null,

    /* Determines the image format of the returned QR code */
    @Json(name = "image_format")
    val imageFormat: QRCustomizations.ImageFormat? = ImageFormat.png,

    /* Removes the Bitly logo from the center of the generated QR image */
    @Json(name = "exclude_bitly_logo")
    val excludeBitlyLogo: kotlin.Boolean? = null

) {

    /**
     * Determines the image format of the returned QR code
     *
     * Values: png,svg
     */
    enum class ImageFormat(val value: kotlin.String) {
        @Json(name = "png") png("png"),
        @Json(name = "svg") svg("svg");
    }
}
