/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param qrLogoImages
 */

data class QRLogoImagesResponse(

    @Json(name = "qr_logo_images")
    val qrLogoImages: kotlin.collections.List<QRLogoImages>? = null

)
