/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param referrers
 * @param network
 */

data class ReferrersByDomain(

    @Json(name = "referrers")
    val referrers: kotlin.collections.List<Metric>? = null,

    @Json(name = "network")
    val network: kotlin.String? = null

)
