/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param units
 * @param facet
 * @param referrersByDomain
 * @param unitReference
 * @param unit
 */

data class ReferrersByDomains(

    @Json(name = "units")
    val units: kotlin.Int? = null,

    @Json(name = "facet")
    val facet: ReferrersByDomains.Facet? = null,

    @Json(name = "referrers_by_domain")
    val referrersByDomain: kotlin.collections.List<ReferrersByDomain>? = null,

    @Json(name = "unit_reference")
    val unitReference: kotlin.String? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null

) {

    /**
     *
     *
     * Values: referrersByDomains
     */
    enum class Facet(val value: kotlin.String) {
        @Json(name = "referrers_by_domains") referrersByDomains("referrers_by_domains");
    }
}
