/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param units
 * @param facet
 * @param unitReference
 * @param unit
 * @param metrics
 */

data class ScanMetrics(

    @Json(name = "units")
    val units: kotlin.Int? = null,

    @Json(name = "facet")
    val facet: ScanMetrics.Facet? = null,

    @Json(name = "unit_reference")
    val unitReference: kotlin.String? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null,

    @Json(name = "metrics")
    val metrics: kotlin.collections.List<ScanMetric>? = null

) {

    /**
     *
     *
     * Values: countries,cities,deviceOs,browsers
     */
    enum class Facet(val value: kotlin.String) {
        @Json(name = "countries") countries("countries"),
        @Json(name = "cities") cities("cities"),
        @Json(name = "device_os") deviceOs("device_os"),
        @Json(name = "browsers") browsers("browsers");
    }
}
