/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param numericId
 * @param accountLogin
 * @param accountType
 * @param accountId
 * @param oauthError
 * @param primary
 * @param visible
 * @param connected ISO timestamp
 * @param accountName
 */

data class ShareAccount(

    @Json(name = "numeric_id")
    val numericId: kotlin.Int? = null,

    @Json(name = "account_login")
    val accountLogin: kotlin.String? = null,

    @Json(name = "account_type")
    val accountType: SocialAccounts? = null,

    @Json(name = "account_id")
    val accountId: kotlin.String? = null,

    @Json(name = "oauth_error")
    val oauthError: kotlin.String? = null,

    @Json(name = "primary")
    val primary: kotlin.Boolean? = null,

    @Json(name = "visible")
    val visible: kotlin.Boolean? = null,

    /* ISO timestamp */
    @Json(name = "connected")
    val connected: kotlin.String? = null,

    @Json(name = "account_name")
    val accountName: kotlin.String? = null

)
