/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param longUrl
 * @param groupGuid
 * @param domain
 */

data class Shorten(

    @Json(name = "long_url")
    val longUrl: kotlin.String,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = "bit.ly"

)
