/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param sortedLinks
 * @param links
 */

data class SortedLinks(

    @Json(name = "sorted_links")
    val sortedLinks: kotlin.collections.List<ClickLink>? = null,

    @Json(name = "links")
    val links: kotlin.collections.List<BitlinkBody>? = null

)
