/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param sloEndpoint
 * @param defaultGroupGuid
 * @param idpUrl
 * @param certificate
 * @param organizationGuid
 * @param samlEndpoint
 * @param identityProvider
 * @param domains
 * @param issuerUrl
 * @param urlSlug
 */

data class SSOSettings(

    @Json(name = "slo_endpoint")
    val sloEndpoint: kotlin.String? = null,

    @Json(name = "default_group_guid")
    val defaultGroupGuid: kotlin.String? = null,

    @Json(name = "idp_url")
    val idpUrl: kotlin.String? = null,

    @Json(name = "certificate")
    val certificate: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null,

    @Json(name = "saml_endpoint")
    val samlEndpoint: kotlin.String? = null,

    @Json(name = "identity_provider")
    val identityProvider: kotlin.String? = null,

    @Json(name = "domains")
    val domains: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "issuer_url")
    val issuerUrl: kotlin.String? = null,

    @Json(name = "url_slug")
    val urlSlug: kotlin.String? = null

)
