/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param available
 * @param urlSlug
 */

data class SSOVerifySlug(

    @Json(name = "available")
    val available: kotlin.Boolean? = null,

    @Json(name = "url_slug")
    val urlSlug: kotlin.String? = null

)
