/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param subscriptionCancelledDate ISO timestamp
 */

data class SubscriptionCancelledDate(

    /* ISO timestamp */
    @Json(name = "subscription_cancelled_date")
    val subscriptionCancelledDate: kotlin.String? = null

)
