/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param thirdPartyAppId
 * @param installUrl
 * @param os
 * @param name
 * @param iconUrl
 */

data class ThirdPartyAppData(

    @Json(name = "third_party_app_id")
    val thirdPartyAppId: kotlin.String? = null,

    @Json(name = "install_url")
    val installUrl: kotlin.String? = null,

    @Json(name = "os")
    val os: ThirdPartyAppData.Os? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "icon_url")
    val iconUrl: kotlin.String? = null

) {

    /**
     *
     *
     * Values: ios,android
     */
    enum class Os(val value: kotlin.String) {
        @Json(name = "ios") ios("ios"),
        @Json(name = "android") android("android");
    }
}
