/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * a single tier
 *
 * @param displayName
 * @param name
 * @param family
 * @param price
 * @param addOnSettings
 * @param billingPeriodType
 * @param consumableFeatures
 * @param sortOrder
 * @param isSelfService
 * @param accessFeatures
 * @param displayIcon
 * @param isPaid
 * @param description
 */

data class Tier(

    @Json(name = "display_name")
    val displayName: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "family")
    val family: Tier.Family,

    @Json(name = "price")
    val price: kotlin.Int,

    @Json(name = "add_on_settings")
    val addOnSettings: kotlin.collections.List<AddOnSetting>,

    @Json(name = "billing_period_type")
    val billingPeriodType: Tier.BillingPeriodType,

    @Json(name = "consumable_features")
    val consumableFeatures: kotlin.collections.List<DefaultConsumableFeature>,

    @Json(name = "sort_order")
    val sortOrder: kotlin.Int,

    @Json(name = "is_self_service")
    val isSelfService: kotlin.Boolean,

    @Json(name = "access_features")
    val accessFeatures: kotlin.collections.List<DefaultAccessFeature>,

    @Json(name = "display_icon")
    val displayIcon: kotlin.String,

    @Json(name = "is_paid")
    val isPaid: kotlin.Boolean,

    @Json(name = "description")
    val description: kotlin.String

) {

    /**
     *
     *
     * Values: basic,company,developer,educator,enterprise,free,premium,pro,spotlight,starter,teams
     */
    enum class Family(val value: kotlin.String) {
        @Json(name = "basic") basic("basic"),
        @Json(name = "company") company("company"),
        @Json(name = "developer") developer("developer"),
        @Json(name = "educator") educator("educator"),
        @Json(name = "enterprise") enterprise("enterprise"),
        @Json(name = "free") free("free"),
        @Json(name = "premium") premium("premium"),
        @Json(name = "pro") pro("pro"),
        @Json(name = "spotlight") spotlight("spotlight"),
        @Json(name = "starter") starter("starter"),
        @Json(name = "teams") teams("teams");
    }
    /**
     *
     *
     * Values: annual,month
     */
    enum class BillingPeriodType(val value: kotlin.String) {
        @Json(name = "annual") annual("annual"),
        @Json(name = "month") month("month");
    }
}
