/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isValid
 * @param isExpired
 */

data class TwoFactorVerify(

    @Json(name = "is_valid")
    val isValid: kotlin.Boolean,

    @Json(name = "is_expired")
    val isExpired: kotlin.Boolean

)
