/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param phoneNumber
 * @param countryCode
 * @param status
 */

data class TwoFactor(

    @Json(name = "phone_number")
    val phoneNumber: kotlin.String,

    @Json(name = "country_code")
    val countryCode: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String? = null

)
