/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isActive
 * @param launchpadId
 * @param domain
 * @param launchpadAppearance
 * @param keyword
 */

data class UpdateLaunchpad(

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "launchpad_id")
    val launchpadId: kotlin.String? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "launchpad_appearance")
    val launchpadAppearance: LaunchpadAppearance? = null,

    @Json(name = "keyword")
    val keyword: kotlin.String? = null

)
