/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param billingInfo
 * @param promoCode
 * @param paymentProvider
 * @param stripeToken
 * @param ratePlanName
 * @param companyName
 * @param orgGuid
 * @param taxId
 * @param paymentMethodId
 */

data class UpgradeOrgBody(

    @Json(name = "billing_info")
    val billingInfo: BillingInfo? = null,

    @Json(name = "promo_code")
    val promoCode: kotlin.String? = null,

    @Json(name = "payment_provider")
    val paymentProvider: UpgradeOrgBody.PaymentProvider? = PaymentProvider.zuora,

    @Json(name = "stripe_token")
    val stripeToken: kotlin.String? = null,

    @Json(name = "rate_plan_name")
    val ratePlanName: kotlin.String? = null,

    @Json(name = "company_name")
    val companyName: kotlin.String? = null,

    @Json(name = "org_guid")
    val orgGuid: kotlin.String? = null,

    @Json(name = "tax_id")
    val taxId: kotlin.String? = null,

    @Json(name = "payment_method_id")
    val paymentMethodId: kotlin.String? = null

) {

    /**
     *
     *
     * Values: zuora,stripe
     */
    enum class PaymentProvider(val value: kotlin.String) {
        @Json(name = "zuora") zuora("zuora"),
        @Json(name = "stripe") stripe("stripe");
    }
}
