/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param firstName
 * @param lastName
 * @param created
 * @param modified
 * @param companySize
 * @param organizationName
 * @param useCases
 * @param version
 * @param useCasesOther
 * @param department
 * @param login
 * @param jobTitle
 * @param departmentOther
 * @param teamType
 */

data class UserOnboardingSurvey(

    @Json(name = "first_name")
    val firstName: kotlin.String? = null,

    @Json(name = "last_name")
    val lastName: kotlin.String? = null,

    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "company_size")
    val companySize: kotlin.String? = null,

    @Json(name = "organization_name")
    val organizationName: kotlin.String? = null,

    @Json(name = "use_cases")
    val useCases: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "version")
    val version: java.math.BigDecimal? = null,

    @Json(name = "use_cases_other")
    val useCasesOther: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "department")
    val department: kotlin.String? = null,

    @Json(name = "login")
    val login: kotlin.String? = null,

    @Json(name = "job_title")
    val jobTitle: kotlin.String? = null,

    @Json(name = "department_other")
    val departmentOther: kotlin.String? = null,

    @Json(name = "team_type")
    val teamType: kotlin.String? = null

)
