/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param isActive
 * @param preference
 * @param `value`
 */

data class UserPreferenceBody(

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "preference")
    val preference: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null

)
