/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param login
 * @param groupGuid
 * @param roleName
 * @param organizationGuid
 */

data class UserRole(

    @Json(name = "login")
    val login: kotlin.String,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "role_name")
    val roleName: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null

)
