/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param defaultGroupGuid
 * @param name
 */

data class UserUpdate(

    @Json(name = "default_group_guid")
    val defaultGroupGuid: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

)
