/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param name
 * @param created
 * @param isActive
 * @param modified
 * @param isSsoUser
 * @param is2faEnabled
 * @param login
 * @param emails
 * @param defaultGroupGuid
 * @param roleName
 */

data class UserInternal(

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "created")
    val created: kotlin.String,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "modified")
    val modified: kotlin.String,

    @Json(name = "is_sso_user")
    val isSsoUser: kotlin.Boolean,

    @Json(name = "is_2fa_enabled")
    val is2faEnabled: kotlin.Boolean,

    @Json(name = "login")
    val login: kotlin.String,

    @Json(name = "emails")
    val emails: kotlin.collections.List<Email>,

    @Json(name = "default_group_guid")
    val defaultGroupGuid: kotlin.String? = null,

    @Json(name = "role_name")
    val roleName: kotlin.String? = null

)
