/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param launchpadViews
 * @param units
 * @param facet
 * @param unit
 * @param unitReference
 */

data class Views(

    @Json(name = "launchpad_views")
    val launchpadViews: kotlin.collections.List<ViewMetric>? = null,

    @Json(name = "units")
    val units: kotlin.Int? = null,

    @Json(name = "facet")
    val facet: Views.Facet? = null,

    @Json(name = "unit")
    val unit: Views.Unit? = null,

    @Json(name = "unit_reference")
    val unitReference: kotlin.String? = null

) {

    /**
     *
     *
     * Values: views,countries,referrers,devices
     */
    enum class Facet(val value: kotlin.String) {
        @Json(name = "views") views("views"),
        @Json(name = "countries") countries("countries"),
        @Json(name = "referrers") referrers("referrers"),
        @Json(name = "devices") devices("devices");
    }
    /**
     *
     *
     * Values: minute,hour,day,week,month
     */
    enum class Unit(val value: kotlin.String) {
        @Json(name = "minute") minute("minute"),
        @Json(name = "hour") hour("hour"),
        @Json(name = "day") day("day"),
        @Json(name = "week") week("week"),
        @Json(name = "month") month("month");
    }
}
