/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param status
 * @param isAlert
 * @param modifiedBy
 * @param name
 * @param created
 * @param url
 * @param deactivated
 * @param fetchTags
 * @param isActive
 * @param modified
 * @param organizationGuid
 * @param alerted
 * @param clientId
 * @param groupGuid
 * @param clientSecret
 * @param oauthUrl
 * @param guid
 * @param event
 */

data class WebhookAllOf(

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "is_alert")
    val isAlert: kotlin.Boolean? = null,

    @Json(name = "modified_by")
    val modifiedBy: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "deactivated")
    val deactivated: kotlin.String? = null,

    @Json(name = "fetch_tags")
    val fetchTags: kotlin.Boolean? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "modified")
    val modified: kotlin.String? = null,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String? = null,

    @Json(name = "alerted")
    val alerted: kotlin.String? = null,

    @Json(name = "client_id")
    val clientId: kotlin.String? = null,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "client_secret")
    val clientSecret: kotlin.String? = null,

    @Json(name = "oauth_url")
    val oauthUrl: kotlin.String? = null,

    @Json(name = "guid")
    val guid: kotlin.String? = null,

    @Json(name = "event")
    val event: kotlin.String? = null

)
