/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param name
 * @param url
 * @param organizationGuid
 * @param event
 * @param groupGuid
 * @param fetchTags
 * @param isActive
 * @param clientId
 * @param clientSecret
 * @param oauthUrl
 */

data class WebhookCreate(

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "organization_guid")
    val organizationGuid: kotlin.String,

    @Json(name = "event")
    val event: kotlin.String,

    @Json(name = "group_guid")
    val groupGuid: kotlin.String? = null,

    @Json(name = "fetch_tags")
    val fetchTags: kotlin.Boolean? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "client_id")
    val clientId: kotlin.String? = null,

    @Json(name = "client_secret")
    val clientSecret: kotlin.String? = null,

    @Json(name = "oauth_url")
    val oauthUrl: kotlin.String? = null

)
